/* This is the script file to create all the tables */

CREATE TABLE OWNER (
	OWNER_ID INT NOT NULL AUTO_INCREMENT,
	OWNER_FNAME VARCHAR(20) NOT NULL,
	OWNER_LNAME VARCHAR(20) NOT NULL,
	OWNER_EMAIL VARCHAR(50) NOT NULL,
	OWNER_JOIN_DATE DATE NOT NULL,
    PRIMARY KEY (OWNER_ID)
);

CREATE TABLE EQUIPMENT (
	EQUIPMENT_ID INT NOT NULL AUTO_INCREMENT,
	EQUIPMENT_DESC VARCHAR(255) NULL,
	EQUIPMENT_COST DECIMAL(8,2) NOT NULL,
	EQUIPMENT_TYPE VARCHAR(30) NOT NULL,
    PRIMARY KEY (EQUIPMENT_ID)
);

CREATE TABLE BOAT (
	BOAT_ID INT NOT NULL AUTO_INCREMENT,
	BOAT_NAME VARCHAR(20) NOT NULL,
	BOAT_SIZE VARCHAR(10) NOT NULL,
	BOAT_RENTAL_COST DECIMAL(8,2) NOT NULL,
	OWNER_ID INT NOT NULL REFERENCES OWNER(OWNER_ID),
    PRIMARY KEY (BOAT_ID)
);

CREATE TABLE LOG (
	LOG_ID INT NOT NULL AUTO_INCREMENT,
	BOAT_ID INT NOT NULL REFERENCES BOAT(BOAT_ID),
	EQUIPMENT_ID INT NOT NULL REFERENCES EQUIPMENT(EQUIPMENT_ID),
	LOG_UNITS DECIMAL (2,0) NOT NULL, 
    PRIMARY KEY (LOG_ID)
);
	
CREATE TABLE MAINTENANCE (
	MAINTENANCE_ID INT NOT NULL AUTO_INCREMENT,
	MAINTENANCE_NAME VARCHAR(20) NOT NULL,
	MAINTENANCE_DESC VARCHAR(255) NULL,
    PRIMARY KEY (MAINTENANCE_ID)
);

CREATE TABLE FACILITY (
	FACILITY_ID INT NOT NULL AUTO_INCREMENT,
	FACILITY_NAME VARCHAR(40) NOT NULL,
	FACILITY_CITY VARCHAR(20) NOT NULL,
	FACILITY_STATE VARCHAR(2) NOT NULL,
    PRIMARY KEY (FACILITY_ID)
);

CREATE TABLE RECORD(
	RECORD_ID INT NOT NULL AUTO_INCREMENT,
	BOAT_ID INT NOT NULL REFERENCES BOAT(BOAT_ID),
	MAINTENANCE_ID INT NOT NULL REFERENCES MAINTENANCE(MAINTENANCE_ID),
	FACILITY_ID INT NOT NULL REFERENCES FACILITY(FACILITY_ID),
	RECORD_COST DECIMAL(8,2) NOT NULL,
    PRIMARY KEY (RECORD_ID)
);

CREATE TABLE CREW (
	CREW_ID INT NOT NULL AUTO_INCREMENT,
	CREW_FNAME VARCHAR(20) NOT NULL,
	CREW_LNAME VARCHAR(20) NOT NULL,
	CREW_HOURLY_WAGE DECIMAL(4,2) NOT NULL,
    PRIMARY KEY (CREW_ID)
);

CREATE TABLE WEATHER (
	WEATHER_ID INT NOT NULL AUTO_INCREMENT,
	WEATHER_DESC VARCHAR(255) NOT NULL,
	WEATHER_PRECIPITATION DECIMAL(3,1) NOT NULL,
	WEATHER_WIND_SPEED DECIMAL (3,1) NOT NULL,
    PRIMARY KEY (WEATHER_ID)
);

CREATE TABLE CUSTOMER (
	CUST_ID INT NOT NULL AUTO_INCREMENT,
	CUST_FNAME VARCHAR(20) NOT NULL,
	CUST_LNAME VARCHAR(20) NOT NULL,
	CUST_EMAIL VARCHAR(50) NOT NULL,
	CUST_BALANCE DECIMAL(8,2) DEFAULT 0.00 NOT NULL,
    PRIMARY KEY (CUST_ID)
);

CREATE TABLE ITINERARY (
	ITINERARY_ID INT NOT NULL AUTO_INCREMENT,
	ITINERARY_NAME VARCHAR(20) NOT NULL,
	ITINERARY_DESC VARCHAR(255) NOT NULL,
	ITINERARY_LOCATION VARCHAR(25) NOT NULL,
    PRIMARY KEY (ITINERARY_ID)
);

CREATE TABLE CHARTER (
	CHARTER_ID INT NOT NULL AUTO_INCREMENT,
	BOAT_ID INT NOT NULL REFERENCES BOAT(BOAT_ID),
	CUST_ID INT NOT NULL REFERENCES CUSTOMER(CUST_ID),
	CREW_ID INT REFERENCES CREW(CREW_ID),
	ITINERARY_ID INT REFERENCES ITINERARY(ITINERARY_ID),
	WEATHER_ID INT REFERENCES WEATHER(WEATHER_ID),
	CHARTER_START_DATE DATE NOT NULL,
	CHARTER_END_DATE DATE NOT NULL,
	CHARTER_RETURN_DATE DATE,
    PRIMARY KEY (CHARTER_ID)
);

CREATE TABLE EMPLOYEE (
    EMPLOYEE_ID INT NOT NULL AUTO_INCREMENT,
    EMPLOYEE_FNAME VARCHAR(20) NOT NULL,
    EMPLOYEE_LNAME VARCHAR(20) NOT NULL,
    EMPLOYEE_EMAIL VARCHAR(50) NOT NULL,
    EMPLOYEE_USERNAME VARCHAR(20) NOT NULL,
    EMPLOYEE_PASSWORD VARCHAR(20) NOT NULL,
    EMPLOYEE_JOIN_DATE DATE NOT NULL,
    PRIMARY KEY (EMPLOYEE_ID)
);


/*
This is to drop all the tables

DROP TABLE EMPLOYEE;
DROP TABLE CHARTER;
DROP TABLE ITINERARY;
DROP TABLE CUSTOMER;
DROP TABLE WEATHER;
DROP TABLE CREW;
DROP TABLE RECORD;
DROP TABLE FACILITY;
DROP TABLE MAINTENANCE;
DROP TABLE LOG;
DROP TABLE BOAT;
DROP TABLE EQUIPMENT;
DROP TABLE OWNER;
*/