/* This is the script file to create all the tables */

CREATE TABLE OWNER (
	OWNER_ID INT NOT NULL AUTO_INCREMENT,
	OWNER_FNAME VARCHAR(20) NOT NULL,
	OWNER_LNAME VARCHAR(20) NOT NULL,
	OWNER_EMAIL VARCHAR(50) NOT NULL,
	OWNER_JOIN_DATE DATE NOT NULL,
    PRIMARY KEY (OWNER_ID)
);

CREATE TABLE EQUIPMENT (
	EQUIPMENT_ID INT NOT NULL AUTO_INCREMENT,
	EQUIPMENT_DESC VARCHAR(255) NULL,
	EQUIPMENT_COST DECIMAL(8,2) NOT NULL,
	EQUIPMENT_TYPE VARCHAR(30) NOT NULL,
    PRIMARY KEY (EQUIPMENT_ID)
);

CREATE TABLE BOAT (
	BOAT_ID INT NOT NULL AUTO_INCREMENT,
	BOAT_NAME VARCHAR(20) NOT NULL,
	BOAT_SIZE VARCHAR(10) NOT NULL,
	BOAT_RENTAL_COST DECIMAL(8,2) NOT NULL,
	OWNER_ID INT NOT NULL REFERENCES OWNER(OWNER_ID),
    PRIMARY KEY (BOAT_ID)
);

CREATE TABLE LOG (
	LOG_ID INT NOT NULL AUTO_INCREMENT,
	BOAT_ID INT NOT NULL REFERENCES BOAT(BOAT_ID),
	EQUIPMENT_ID INT NOT NULL REFERENCES EQUIPMENT(EQUIPMENT_ID),
	LOG_UNITS DECIMAL (2,0) NOT NULL, 
    PRIMARY KEY (LOG_ID)
);
	
CREATE TABLE MAINTENANCE (
	MAINTENANCE_ID INT NOT NULL AUTO_INCREMENT,
	MAINTENANCE_NAME VARCHAR(20) NOT NULL,
	MAINTENANCE_DESC VARCHAR(255) NULL,
    PRIMARY KEY (MAINTENANCE_ID)
);

CREATE TABLE FACILITY (
	FACILITY_ID INT NOT NULL AUTO_INCREMENT,
	FACILITY_NAME VARCHAR(40) NOT NULL,
	FACILITY_CITY VARCHAR(20) NOT NULL,
	FACILITY_STATE VARCHAR(2) NOT NULL,
    PRIMARY KEY (FACILITY_ID)
);

CREATE TABLE RECORD(
	RECORD_ID INT NOT NULL AUTO_INCREMENT,
	BOAT_ID INT NOT NULL REFERENCES BOAT(BOAT_ID),
	MAINTENANCE_ID INT NOT NULL REFERENCES MAINTENANCE(MAINTENANCE_ID),
	FACILITY_ID INT NOT NULL REFERENCES FACILITY(FACILITY_ID),
	RECORD_COST DECIMAL(8,2) NOT NULL,
    PRIMARY KEY (RECORD_ID)
);

CREATE TABLE CREW (
	CREW_ID INT NOT NULL AUTO_INCREMENT,
	CREW_FNAME VARCHAR(20) NOT NULL,
	CREW_LNAME VARCHAR(20) NOT NULL,
	CREW_HOURLY_WAGE DECIMAL(4,2) NOT NULL,
    PRIMARY KEY (CREW_ID)
);

CREATE TABLE WEATHER (
	WEATHER_ID INT NOT NULL AUTO_INCREMENT,
	WEATHER_DESC VARCHAR(255) NOT NULL,
	WEATHER_PRECIPITATION DECIMAL(3,1) NOT NULL,
	WEATHER_WIND_SPEED DECIMAL (3,1) NOT NULL,
    PRIMARY KEY (WEATHER_ID)
);

CREATE TABLE CUSTOMER (
	CUST_ID INT NOT NULL AUTO_INCREMENT,
	CUST_FNAME VARCHAR(20) NOT NULL,
	CUST_LNAME VARCHAR(20) NOT NULL,
	CUST_EMAIL VARCHAR(50) NOT NULL,
	CUST_BALANCE DECIMAL(8,2) DEFAULT 0.00 NOT NULL,
    PRIMARY KEY (CUST_ID)
);

CREATE TABLE ITINERARY (
	ITINERARY_ID INT NOT NULL AUTO_INCREMENT,
	ITINERARY_NAME VARCHAR(20) NOT NULL,
	ITINERARY_DESC VARCHAR(255) NOT NULL,
	ITINERARY_LOCATION VARCHAR(25) NOT NULL,
    PRIMARY KEY (ITINERARY_ID)
);

CREATE TABLE CHARTER (
	CHARTER_ID INT NOT NULL AUTO_INCREMENT,
	BOAT_ID INT NOT NULL REFERENCES BOAT(BOAT_ID),
	CUST_ID INT NOT NULL REFERENCES CUSTOMER(CUST_ID),
	CREW_ID INT REFERENCES CREW(CREW_ID),
	ITINERARY_ID INT REFERENCES ITINERARY(ITINERARY_ID),
	WEATHER_ID INT REFERENCES WEATHER(WEATHER_ID),
	CHARTER_START_DATE DATE NOT NULL,
	CHARTER_END_DATE DATE NOT NULL,
	CHARTER_RETURN_DATE DATE,
    PRIMARY KEY (CHARTER_ID)
);

CREATE TABLE EMPLOYEE (
    EMPLOYEE_ID INT NOT NULL AUTO_INCREMENT,
    EMPLOYEE_FNAME VARCHAR(20) NOT NULL,
    EMPLOYEE_LNAME VARCHAR(20) NOT NULL,
    EMPLOYEE_EMAIL VARCHAR(50) NOT NULL,
    EMPLOYEE_USERNAME VARCHAR(20) NOT NULL,
    EMPLOYEE_PASSWORD VARCHAR(20) NOT NULL,
    EMPLOYEE_JOIN_DATE DATE NOT NULL,
    PRIMARY KEY (EMPLOYEE_ID)
);


/*
This is to drop all the tables

DROP TABLE EMPLOYEE;
DROP TABLE CHARTER;
DROP TABLE ITINERARY;
DROP TABLE CUSTOMER;
DROP TABLE WEATHER;
DROP TABLE CREW;
DROP TABLE RECORD;
DROP TABLE FACILITY;
DROP TABLE MAINTENANCE;
DROP TABLE LOG;
DROP TABLE BOAT;
DROP TABLE EQUIPMENT;
DROP TABLE OWNER;
*/


/*



The following section populates the tables with information



*/

-- OWNNER rows 
INSERT INTO OWNER (OWNER_FNAME, OWNER_LNAME, OWNER_EMAIL, OWNER_JOIN_DATE) VALUES('Jack', 'Shephard', 'Jack.Shepard@Oceanic.com', '2019-12-03');
INSERT INTO OWNER (OWNER_FNAME, OWNER_LNAME, OWNER_EMAIL, OWNER_JOIN_DATE) VALUES('Kate', 'Austen', 'Kate.Austen@Oceanic.com', '2017-05-11');
INSERT INTO OWNER (OWNER_FNAME, OWNER_LNAME, OWNER_EMAIL, OWNER_JOIN_DATE) VALUES('Hugo', 'Reyes', 'Hugo.Reyes@Oceanic.com', '2018-12-29');
INSERT INTO OWNER (OWNER_FNAME, OWNER_LNAME, OWNER_EMAIL, OWNER_JOIN_DATE) VALUES('Sayid', 'Jarrah', 'Sayid.Jarrah@Oceanic.com', '2017-11-07');
INSERT INTO OWNER (OWNER_FNAME, OWNER_LNAME, OWNER_EMAIL, OWNER_JOIN_DATE) VALUES('Sun-Hwa', 'Kwon', 'Sun-Hwa.Kwon@Oceanic.com', '2020-03-20');
INSERT INTO OWNER (OWNER_FNAME, OWNER_LNAME, OWNER_EMAIL, OWNER_JOIN_DATE) VALUES('Aaron', 'Littleton', 'Aaron.Littleton@Oceanic.com', '2021-11-01');

-- EQUIPMENT rows
INSERT INTO EQUIPMENT (EQUIPMENT_DESC, EQUIPMENT_COST, EQUIPMENT_TYPE) VALUES('40in x 12.83in Fully Battened Mainsail', 2389.00, 'Sail');
INSERT INTO EQUIPMENT (EQUIPMENT_DESC, EQUIPMENT_COST, EQUIPMENT_TYPE) VALUES('Levante Downwind Sail', 11543.40, 'Sail');
INSERT INTO EQUIPMENT (EQUIPMENT_DESC, EQUIPMENT_COST, EQUIPMENT_TYPE) VALUES('D12 MAX 78 Rigging Rope', 380.77, 'Lines');
INSERT INTO EQUIPMENT (EQUIPMENT_DESC, EQUIPMENT_COST, EQUIPMENT_TYPE) VALUES('Marlow Double Braid Polyester Marine Rope', 173.62, 'Lines');
INSERT INTO EQUIPMENT (EQUIPMENT_DESC, EQUIPMENT_COST, EQUIPMENT_TYPE) VALUES('ALL-PAX Passenger Life Preserver', 359.00, 'Life Preserver');
INSERT INTO EQUIPMENT (EQUIPMENT_DESC, EQUIPMENT_COST, EQUIPMENT_TYPE) VALUES('30" USCG Ring Buoy', 91.00, 'Life Preserver');
INSERT INTO EQUIPMENT (EQUIPMENT_DESC, EQUIPMENT_COST, EQUIPMENT_TYPE) VALUES('Gibson Home 95-Piece Complete Kitchen Kit', 99.98, 'Kitchen Equipment'); 
INSERT INTO EQUIPMENT (EQUIPMENT_DESC, EQUIPMENT_COST, EQUIPMENT_TYPE) VALUES('Palm Island Bedcover and Shams', 1320.00, 'Bedding');
INSERT INTO EQUIPMENT (EQUIPMENT_DESC, EQUIPMENT_COST, EQUIPMENT_TYPE) VALUES('Navigation Book', 35.00, 'Caribban Provided');

-- BOAT rows
INSERT INTO BOAT (BOAT_NAME, BOAT_SIZE, BOAT_RENTAL_COST, OWNER_ID) VALUES('Gale', 'Small', 235, 6);
INSERT INTO BOAT (BOAT_NAME, BOAT_SIZE, BOAT_RENTAL_COST, OWNER_ID) VALUES('Liberty', 'Medium', 445, 1);
INSERT INTO BOAT (BOAT_NAME, BOAT_SIZE, BOAT_RENTAL_COST, OWNER_ID) VALUES('Serendipity', 'Small', 270, 5);
INSERT INTO BOAT (BOAT_NAME, BOAT_SIZE, BOAT_RENTAL_COST, OWNER_ID) VALUES('Atlantis', 'Medium', 510, 4);
INSERT INTO BOAT (BOAT_NAME, BOAT_SIZE, BOAT_RENTAL_COST, OWNER_ID) VALUES('Leviathan', 'Large', 975, 3);
INSERT INTO BOAT (BOAT_NAME, BOAT_SIZE, BOAT_RENTAL_COST, OWNER_ID) VALUES('Neptune', 'Large', 850, 3);
INSERT INTO BOAT (BOAT_NAME, BOAT_SIZE, BOAT_RENTAL_COST, OWNER_ID) VALUES('Wayfarer', 'Medium', 480, 2);

-- LOG rows
INSERT INTO LOG (BOAT_ID, EQUIPMENT_ID, LOG_UNITS) VALUES(1, 1, 1);
INSERT INTO LOG (BOAT_ID, EQUIPMENT_ID, LOG_UNITS) VALUES(1, 3, 1);
INSERT INTO LOG (BOAT_ID, EQUIPMENT_ID, LOG_UNITS) VALUES(1, 5, 2);
INSERT INTO LOG (BOAT_ID, EQUIPMENT_ID, LOG_UNITS) VALUES(1, 6, 1);
INSERT INTO LOG (BOAT_ID, EQUIPMENT_ID, LOG_UNITS) VALUES(6, 2, 2);
INSERT INTO LOG (BOAT_ID, EQUIPMENT_ID, LOG_UNITS) VALUES(6, 4, 2);
INSERT INTO LOG (BOAT_ID, EQUIPMENT_ID, LOG_UNITS) VALUES(6, 5, 8);
INSERT INTO LOG (BOAT_ID, EQUIPMENT_ID, LOG_UNITS) VALUES(6, 6, 2);
INSERT INTO LOG (BOAT_ID, EQUIPMENT_ID, LOG_UNITS) VALUES(6, 7, 1);
INSERT INTO LOG (BOAT_ID, EQUIPMENT_ID, LOG_UNITS) VALUES(6, 8, 1);

-- MAINTENANCE rows
INSERT INTO MAINTENANCE (MAINTENANCE_NAME, MAINTENANCE_DESC) VALUES('Sail Patch', 'A temporary patch on the sails.');
INSERT INTO MAINTENANCE (MAINTENANCE_NAME, MAINTENANCE_DESC) VALUES('Hull Repair', 'Fixing extensive damage to the hull.');
INSERT INTO MAINTENANCE (MAINTENANCE_NAME, MAINTENANCE_DESC) VALUES('Rudder Repair', 'Reattaching and testing rudder controls.');
INSERT INTO MAINTENANCE (MAINTENANCE_NAME, MAINTENANCE_DESC) VALUES('Mast Repair', 'Fortifying damaged mast.');
INSERT INTO MAINTENANCE (MAINTENANCE_NAME, MAINTENANCE_DESC) VALUES('Anchor Replacement', 'Replacing anchor and wench');

-- FACILITY rows
INSERT INTO FACILITY (FACILITY_NAME, FACILITY_CITY, FACILITY_STATE) VALUES('Dharma Repairs', 'Fort Meyers', 'FL');
INSERT INTO FACILITY (FACILITY_NAME, FACILITY_CITY, FACILITY_STATE) VALUES('Widmore Marine Parts', 'Pensacola', 'FL');
INSERT INTO FACILITY (FACILITY_NAME, FACILITY_CITY, FACILITY_STATE) VALUES('St. Sebastian Repair', 'Gulfport', 'MS');
INSERT INTO FACILITY (FACILITY_NAME, FACILITY_CITY, FACILITY_STATE) VALUES('Kluck Boat Works', 'Cape Coral', 'FL');
INSERT INTO FACILITY (FACILITY_NAME, FACILITY_CITY, FACILITY_STATE) VALUES('The Island Marine', 'Fort Meyers', 'FL');

-- RECORD rows
INSERT INTO RECORD (BOAT_ID, MAINTENANCE_ID, FACILITY_ID, RECORD_COST) VALUES(1, 1, 2, 139.00);
INSERT INTO RECORD (BOAT_ID, MAINTENANCE_ID, FACILITY_ID, RECORD_COST) VALUES(6, 2, 4, 3475.00);
INSERT INTO RECORD (BOAT_ID, MAINTENANCE_ID, FACILITY_ID, RECORD_COST) VALUES(6, 3, 4, 320.00);
INSERT INTO RECORD (BOAT_ID, MAINTENANCE_ID, FACILITY_ID, RECORD_COST) VALUES(6, 4, 4, 1225.00);
INSERT INTO RECORD (BOAT_ID, MAINTENANCE_ID, FACILITY_ID, RECORD_COST) VALUES(2, 1, 1, 189.99);

-- CREW rows
INSERT INTO CREW (CREW_FNAME, CREW_LNAME, CREW_HOURLY_WAGE) VALUES('Richard', 'Alpert', 35.00);
INSERT INTO CREW (CREW_FNAME, CREW_LNAME, CREW_HOURLY_WAGE) VALUES('Dogen', 'Temple', 42.00);
INSERT INTO CREW (CREW_FNAME, CREW_LNAME, CREW_HOURLY_WAGE) VALUES('Lennon', 'Temple', 38.00);
INSERT INTO CREW (CREW_FNAME, CREW_LNAME, CREW_HOURLY_WAGE) VALUES('Ben', 'Linus', 21.00);
INSERT INTO CREW (CREW_FNAME, CREW_LNAME, CREW_HOURLY_WAGE) VALUES('Juliet', 'Burke', 29.00);

-- WEATHER rows
INSERT INTO WEATHER (WEATHER_DESC, WEATHER_PRECIPITATION, WEATHER_WIND_SPEED) VALUES('Overcast with light rain', 3, 5);
INSERT INTO WEATHER (WEATHER_DESC, WEATHER_PRECIPITATION, WEATHER_WIND_SPEED) VALUES('Sunny clear skies', 0, 4);
INSERT INTO WEATHER (WEATHER_DESC, WEATHER_PRECIPITATION, WEATHER_WIND_SPEED) VALUES('Sunny clear skies with light wind', 0, 9);
INSERT INTO WEATHER (WEATHER_DESC, WEATHER_PRECIPITATION, WEATHER_WIND_SPEED) VALUES('Heavy Storm', 33, 21);
INSERT INTO WEATHER (WEATHER_DESC, WEATHER_PRECIPITATION, WEATHER_WIND_SPEED) VALUES('Overcast with heavy rain', 21, 12);

-- CUSTOMER rows
INSERT INTO CUSTOMER (CUST_FNAME, CUST_LNAME, CUST_EMAIL) VALUES('James', 'Sawyer', 'James.Sawyer@gmail.com');
INSERT INTO CUSTOMER (CUST_FNAME, CUST_LNAME, CUST_EMAIL, CUST_BALANCE) VALUES('Claire', 'Littleton', 'Claire.Littleton@gmail.com', 240.00);
INSERT INTO CUSTOMER (CUST_FNAME, CUST_LNAME, CUST_EMAIL) VALUES('Rose', 'Nadler', 'Rose.Nadler@gmail.com');
INSERT INTO CUSTOMER (CUST_FNAME, CUST_LNAME, CUST_EMAIL, CUST_BALANCE) VALUES('Jin-Soo', 'Kwon', 'Jin-Soo.Kwon@gmail.com', 125.00);
INSERT INTO CUSTOMER (CUST_FNAME, CUST_LNAME, CUST_EMAIL, CUST_BALANCE) VALUES('John', 'Locke', 'John.Locke@gmail.com', 84.00);
INSERT INTO CUSTOMER (CUST_FNAME, CUST_LNAME, CUST_EMAIL, CUST_BALANCE) VALUES('Bernard', 'Nadler', 'Bernard.Nadler@gmail.com', 12.00);
INSERT INTO CUSTOMER (CUST_FNAME, CUST_LNAME, CUST_EMAIL, CUST_BALANCE) VALUES('Shannon', 'Rutherford', 'Shannon.Rutherford@gmail.com', 5000.00);
INSERT INTO CUSTOMER (CUST_FNAME, CUST_LNAME, CUST_EMAIL, CUST_BALANCE) VALUES('Walt', 'Lloyd', 'Walt.Lloyd@gmail.com', 150.00);
INSERT INTO CUSTOMER (CUST_FNAME, CUST_LNAME, CUST_EMAIL, CUST_BALANCE) VALUES('Charlie', 'Pace', 'Charlie.Pace@gmail.com', 230.00);
INSERT INTO CUSTOMER (CUST_FNAME, CUST_LNAME, CUST_EMAIL, CUST_BALANCE) VALUES('Libby', 'Smith', 'Libby.Smith@gmail.com', 45.00);
INSERT INTO CUSTOMER (CUST_FNAME, CUST_LNAME, CUST_EMAIL, CUST_BALANCE) VALUES('Desmond', 'Hume', 'Desmond.Hume@gmail.com', 120.00);
INSERT INTO CUSTOMER (CUST_FNAME, CUST_LNAME, CUST_EMAIL, CUST_BALANCE) VALUES('Nikki', 'Fernandez', 'Nikki.Fernandez@gmail.com', 98.00);
INSERT INTO CUSTOMER (CUST_FNAME, CUST_LNAME, CUST_EMAIL, CUST_BALANCE) VALUES('Daniel', 'Faraday', 'Daniel.Faraday@gmail.com', 250.00);
INSERT INTO CUSTOMER (CUST_FNAME, CUST_LNAME, CUST_EMAIL, CUST_BALANCE) VALUES('Eko', 'Man', 'Eko.Man@gmail.com', 170.00);
INSERT INTO CUSTOMER (CUST_FNAME, CUST_LNAME, CUST_EMAIL, CUST_BALANCE) VALUES('Charlotte', 'Lewis', 'Charlotte.Lewis@gmail.com', 85.00);
INSERT INTO CUSTOMER (CUST_FNAME, CUST_LNAME, CUST_EMAIL, CUST_BALANCE) VALUES('Frank', 'Lapidus', 'Frank.Lapidus@gmail.com', 66.00);
INSERT INTO CUSTOMER (CUST_FNAME, CUST_LNAME, CUST_EMAIL, CUST_BALANCE) VALUES('Ilana', 'Verdansky', 'Ilana.Verdansky@gmail.com', 110.00);
INSERT INTO CUSTOMER (CUST_FNAME, CUST_LNAME, CUST_EMAIL, CUST_BALANCE) VALUES('Eloise', 'Hawking', 'Eloise.Hawking@gmail.com', 30.00);
INSERT INTO CUSTOMER (CUST_FNAME, CUST_LNAME, CUST_EMAIL, CUST_BALANCE) VALUES('Christian', 'Shephard', 'Christian.Shephard@gmail.com', 200.00);
INSERT INTO CUSTOMER (CUST_FNAME, CUST_LNAME, CUST_EMAIL, CUST_BALANCE) VALUES('Penny', 'Widmore', 'Penny.Widmore@gmail.com', 250.00);


-- ITINERARY rows
INSERT INTO ITINERARY (ITINERARY_NAME, ITINERARY_DESC, ITINERARY_LOCATION) VALUES('Coastal Venture', 'Ride along the coast of Florida', 'Florida');
INSERT INTO ITINERARY (ITINERARY_NAME, ITINERARY_DESC, ITINERARY_LOCATION) VALUES('Island Hopping', 'Hop island-to-island on this fun excursion', 'Florida');
INSERT INTO ITINERARY (ITINERARY_NAME, ITINERARY_DESC, ITINERARY_LOCATION) VALUES('Deep Sea Venture', 'Head out to explore the Deep Sea for some remote fun!', 'Mississippi');
INSERT INTO ITINERARY (ITINERARY_NAME, ITINERARY_DESC, ITINERARY_LOCATION) VALUES('Diving Adventure', 'Explore all the beautiful coast reefs and stop by old wreckage', 'Florida');
INSERT INTO ITINERARY (ITINERARY_NAME, ITINERARY_DESC, ITINERARY_LOCATION) VALUES('Exploring the Gulf', 'Set sails and tour all the Gulf has to offer!', 'Mississippi');

-- CHARTER rows
INSERT INTO CHARTER (BOAT_ID, CUST_ID, CREW_ID, ITINERARY_ID, WEATHER_ID, CHARTER_START_DATE, CHARTER_END_DATE, CHARTER_RETURN_DATE) VALUES(1, 7, NULL, 2, 2, '2024-05-12', '2024-05-16', '2024-05-16');
INSERT INTO CHARTER (BOAT_ID, CUST_ID, CREW_ID, ITINERARY_ID, WEATHER_ID, CHARTER_START_DATE, CHARTER_END_DATE, CHARTER_RETURN_DATE) VALUES(1, 2, NULL, 1, 2, '2024-05-15', '2024-05-25', '2024-05-22');
INSERT INTO CHARTER (BOAT_ID, CUST_ID, CREW_ID, ITINERARY_ID, WEATHER_ID, CHARTER_START_DATE, CHARTER_END_DATE, CHARTER_RETURN_DATE) VALUES(2, 5, 1, 3, 2, '2024-06-30', '2024-07-02', '2024-07-03');
INSERT INTO CHARTER (BOAT_ID, CUST_ID, CREW_ID, ITINERARY_ID, WEATHER_ID, CHARTER_START_DATE, CHARTER_END_DATE, CHARTER_RETURN_DATE) VALUES(6, 1, 5, 2, 3, '2024-07-18', '2024-07-21', '2024-07-22');
INSERT INTO CHARTER (BOAT_ID, CUST_ID, CREW_ID, ITINERARY_ID, WEATHER_ID, CHARTER_START_DATE, CHARTER_END_DATE, CHARTER_RETURN_DATE) VALUES(2, 3, 3, 3, 2, '2024-08-21', '2024-08-23', '2024-08-23');
INSERT INTO CHARTER (BOAT_ID, CUST_ID, CREW_ID, ITINERARY_ID, WEATHER_ID, CHARTER_START_DATE, CHARTER_END_DATE, CHARTER_RETURN_DATE) VALUES(4, 4, 5, 5, 1, '2024-08-24', '2024-08-30', '2024-08-30');
INSERT INTO CHARTER (BOAT_ID, CUST_ID, CREW_ID, ITINERARY_ID, WEATHER_ID, CHARTER_START_DATE, CHARTER_END_DATE, CHARTER_RETURN_DATE) VALUES(5, 7, 2, 2, 5, '2024-08-29', '2024-09-05', '2024-09-05');
INSERT INTO CHARTER (BOAT_ID, CUST_ID, CREW_ID, ITINERARY_ID, WEATHER_ID, CHARTER_START_DATE, CHARTER_END_DATE, CHARTER_RETURN_DATE) VALUES(1, 6, NULL, 4, 1, '2024-09-08', '2024-09-11', '2024-09-11');
INSERT INTO CHARTER (BOAT_ID, CUST_ID, CREW_ID, ITINERARY_ID, WEATHER_ID, CHARTER_START_DATE, CHARTER_END_DATE, CHARTER_RETURN_DATE) VALUES(1, 5, NULL, NULL, 1, '2023-03-10', '2023-03-13', '2023-03-12');
INSERT INTO CHARTER (BOAT_ID, CUST_ID, CREW_ID, ITINERARY_ID, WEATHER_ID, CHARTER_START_DATE, CHARTER_END_DATE, CHARTER_RETURN_DATE) VALUES(2, 8, NULL, NULL, 2, '2023-04-05', '2023-04-09', '2023-04-09');
INSERT INTO CHARTER (BOAT_ID, CUST_ID, CREW_ID, ITINERARY_ID, WEATHER_ID, CHARTER_START_DATE, CHARTER_END_DATE, CHARTER_RETURN_DATE) VALUES(3, 14, NULL, NULL, 1, '2023-05-15', '2023-05-18', '2023-05-17');
INSERT INTO CHARTER (BOAT_ID, CUST_ID, CREW_ID, ITINERARY_ID, WEATHER_ID, CHARTER_START_DATE, CHARTER_END_DATE, CHARTER_RETURN_DATE) VALUES(4, 10, NULL, NULL, 2, '2023-06-01', '2023-06-04', '2023-06-03');
INSERT INTO CHARTER (BOAT_ID, CUST_ID, CREW_ID, ITINERARY_ID, WEATHER_ID, CHARTER_START_DATE, CHARTER_END_DATE, CHARTER_RETURN_DATE) VALUES(5, 2, NULL, NULL, 1, '2023-07-20', '2023-07-22', '2023-07-23');
INSERT INTO CHARTER (BOAT_ID, CUST_ID, CREW_ID, ITINERARY_ID, WEATHER_ID, CHARTER_START_DATE, CHARTER_END_DATE, CHARTER_RETURN_DATE) VALUES(6, 16, NULL, NULL, 2, '2023-08-05', '2023-08-07', '2023-08-06');
INSERT INTO CHARTER (BOAT_ID, CUST_ID, CREW_ID, ITINERARY_ID, WEATHER_ID, CHARTER_START_DATE, CHARTER_END_DATE, CHARTER_RETURN_DATE) VALUES(7, 3, NULL, NULL, 1, '2023-09-10', '2023-09-13', '2023-09-12');
INSERT INTO CHARTER (BOAT_ID, CUST_ID, CREW_ID, ITINERARY_ID, WEATHER_ID, CHARTER_START_DATE, CHARTER_END_DATE, CHARTER_RETURN_DATE) VALUES(1, 18, NULL, NULL, 2, '2023-10-08', '2023-10-12', '2023-10-12');
INSERT INTO CHARTER (BOAT_ID, CUST_ID, CREW_ID, ITINERARY_ID, WEATHER_ID, CHARTER_START_DATE, CHARTER_END_DATE, CHARTER_RETURN_DATE) VALUES(2, 4, NULL, NULL, 1, '2023-11-03', '2023-11-06', '2023-11-05');
INSERT INTO CHARTER (BOAT_ID, CUST_ID, CREW_ID, ITINERARY_ID, WEATHER_ID, CHARTER_START_DATE, CHARTER_END_DATE, CHARTER_RETURN_DATE) VALUES(3, 9, NULL, NULL, 2, '2023-12-20', '2023-12-24', '2023-12-23');
INSERT INTO CHARTER (BOAT_ID, CUST_ID, CREW_ID, ITINERARY_ID, WEATHER_ID, CHARTER_START_DATE, CHARTER_END_DATE, CHARTER_RETURN_DATE) VALUES(4, 6, NULL, NULL, 1, '2023-03-25', '2023-03-28', '2023-03-27');
INSERT INTO CHARTER (BOAT_ID, CUST_ID, CREW_ID, ITINERARY_ID, WEATHER_ID, CHARTER_START_DATE, CHARTER_END_DATE, CHARTER_RETURN_DATE) VALUES(5, 19, NULL, NULL, 2, '2023-04-16', '2023-04-18', '2023-04-18');
INSERT INTO CHARTER (BOAT_ID, CUST_ID, CREW_ID, ITINERARY_ID, WEATHER_ID, CHARTER_START_DATE, CHARTER_END_DATE, CHARTER_RETURN_DATE) VALUES(6, 7, NULL, NULL, 1, '2023-05-23', '2023-05-27', '2023-05-26');
INSERT INTO CHARTER (BOAT_ID, CUST_ID, CREW_ID, ITINERARY_ID, WEATHER_ID, CHARTER_START_DATE, CHARTER_END_DATE, CHARTER_RETURN_DATE) VALUES(7, 12, NULL, NULL, 2, '2023-06-19', '2023-06-21', '2023-06-20');
INSERT INTO CHARTER (BOAT_ID, CUST_ID, CREW_ID, ITINERARY_ID, WEATHER_ID, CHARTER_START_DATE, CHARTER_END_DATE, CHARTER_RETURN_DATE) VALUES(1, 11, NULL, NULL, 1, '2023-07-30', '2023-08-02', '2023-08-01');
INSERT INTO CHARTER (BOAT_ID, CUST_ID, CREW_ID, ITINERARY_ID, WEATHER_ID, CHARTER_START_DATE, CHARTER_END_DATE, CHARTER_RETURN_DATE) VALUES(2, 20, NULL, NULL, 2, '2023-09-18', '2023-09-21', '2023-09-20');
INSERT INTO CHARTER (BOAT_ID, CUST_ID, CREW_ID, ITINERARY_ID, WEATHER_ID, CHARTER_START_DATE, CHARTER_END_DATE, CHARTER_RETURN_DATE) VALUES(3, 15, NULL, NULL, 1, '2023-10-22', '2023-10-26', '2023-10-25');
INSERT INTO CHARTER (BOAT_ID, CUST_ID, CREW_ID, ITINERARY_ID, WEATHER_ID, CHARTER_START_DATE, CHARTER_END_DATE, CHARTER_RETURN_DATE) VALUES(4, 13, NULL, NULL, 2, '2023-11-12', '2023-11-16', '2023-11-15');
INSERT INTO CHARTER (BOAT_ID, CUST_ID, CREW_ID, ITINERARY_ID, WEATHER_ID, CHARTER_START_DATE, CHARTER_END_DATE, CHARTER_RETURN_DATE) VALUES(5, 1, NULL, NULL, 1, '2023-12-01', '2023-12-04', '2023-12-03');
INSERT INTO CHARTER (BOAT_ID, CUST_ID, CREW_ID, ITINERARY_ID, WEATHER_ID, CHARTER_START_DATE, CHARTER_END_DATE, CHARTER_RETURN_DATE) VALUES(6, 17, NULL, NULL, 2, '2023-12-27', '2023-12-30', '2023-12-30');
INSERT INTO CHARTER (BOAT_ID, CUST_ID, CREW_ID, ITINERARY_ID, WEATHER_ID, CHARTER_START_DATE, CHARTER_END_DATE, CHARTER_RETURN_DATE) VALUES (1, 3, NULL, NULL, 1, '2024-01-05', '2024-01-07', '2024-01-06');
INSERT INTO CHARTER (BOAT_ID, CUST_ID, CREW_ID, ITINERARY_ID, WEATHER_ID, CHARTER_START_DATE, CHARTER_END_DATE, CHARTER_RETURN_DATE) VALUES (3, 12, NULL, NULL, 2, '2024-01-20', '2024-01-23', '2024-01-22');
INSERT INTO CHARTER (BOAT_ID, CUST_ID, CREW_ID, ITINERARY_ID, WEATHER_ID, CHARTER_START_DATE, CHARTER_END_DATE, CHARTER_RETURN_DATE) VALUES (2, 8, NULL, NULL, 2, '2024-02-15', '2024-02-18', '2024-02-17');
INSERT INTO CHARTER (BOAT_ID, CUST_ID, CREW_ID, ITINERARY_ID, WEATHER_ID, CHARTER_START_DATE, CHARTER_END_DATE, CHARTER_RETURN_DATE) VALUES (4, 18, NULL, NULL, 1, '2024-02-28', '2024-03-02', '2024-03-01');
INSERT INTO CHARTER (BOAT_ID, CUST_ID, CREW_ID, ITINERARY_ID, WEATHER_ID, CHARTER_START_DATE, CHARTER_END_DATE, CHARTER_RETURN_DATE) VALUES (3, 10, NULL, NULL, 1, '2024-03-20', '2024-03-24', '2024-03-23');
INSERT INTO CHARTER (BOAT_ID, CUST_ID, CREW_ID, ITINERARY_ID, WEATHER_ID, CHARTER_START_DATE, CHARTER_END_DATE, CHARTER_RETURN_DATE) VALUES (4, 14, NULL, NULL, 2, '2024-04-10', '2024-04-13', '2024-04-12');
INSERT INTO CHARTER (BOAT_ID, CUST_ID, CREW_ID, ITINERARY_ID, WEATHER_ID, CHARTER_START_DATE, CHARTER_END_DATE, CHARTER_RETURN_DATE) VALUES (5, 16, NULL, NULL, 1, '2024-05-07', '2024-05-10', '2024-05-09');
INSERT INTO CHARTER (BOAT_ID, CUST_ID, CREW_ID, ITINERARY_ID, WEATHER_ID, CHARTER_START_DATE, CHARTER_END_DATE, CHARTER_RETURN_DATE) VALUES (6, 5, NULL, NULL, 2, '2024-06-15', '2024-06-19', '2024-06-18');
INSERT INTO CHARTER (BOAT_ID, CUST_ID, CREW_ID, ITINERARY_ID, WEATHER_ID, CHARTER_START_DATE, CHARTER_END_DATE, CHARTER_RETURN_DATE) VALUES (7, 9, NULL, NULL, 1, '2024-07-22', '2024-07-25', '2024-07-24');
INSERT INTO CHARTER (BOAT_ID, CUST_ID, CREW_ID, ITINERARY_ID, WEATHER_ID, CHARTER_START_DATE, CHARTER_END_DATE, CHARTER_RETURN_DATE) VALUES (1, 20, NULL, NULL, 2, '2024-08-03', '2024-08-06', '2024-08-05');
INSERT INTO CHARTER (BOAT_ID, CUST_ID, CREW_ID, ITINERARY_ID, WEATHER_ID, CHARTER_START_DATE, CHARTER_END_DATE, CHARTER_RETURN_DATE) VALUES (2, 4, NULL, NULL, 1, '2024-09-10', '2024-09-14', '2024-09-13');
INSERT INTO CHARTER (BOAT_ID, CUST_ID, CREW_ID, ITINERARY_ID, WEATHER_ID, CHARTER_START_DATE, CHARTER_END_DATE, CHARTER_RETURN_DATE) VALUES (5, 6, NULL, NULL, 2, '2024-04-25', '2024-04-29', '2024-04-28');
INSERT INTO CHARTER (BOAT_ID, CUST_ID, CREW_ID, ITINERARY_ID, WEATHER_ID, CHARTER_START_DATE, CHARTER_END_DATE, CHARTER_RETURN_DATE) VALUES (6, 15, NULL, NULL, 1, '2024-05-18', '2024-05-22', '2024-05-21');
INSERT INTO CHARTER (BOAT_ID, CUST_ID, CREW_ID, ITINERARY_ID, WEATHER_ID, CHARTER_START_DATE, CHARTER_END_DATE, CHARTER_RETURN_DATE) VALUES (7, 11, NULL, NULL, 2, '2024-06-12', '2024-06-15', '2024-06-14');
INSERT INTO CHARTER (BOAT_ID, CUST_ID, CREW_ID, ITINERARY_ID, WEATHER_ID, CHARTER_START_DATE, CHARTER_END_DATE, CHARTER_RETURN_DATE) VALUES (1, 1, NULL, NULL, 1, '2024-07-05', '2024-07-08', '2024-07-07');
INSERT INTO CHARTER (BOAT_ID, CUST_ID, CREW_ID, ITINERARY_ID, WEATHER_ID, CHARTER_START_DATE, CHARTER_END_DATE, CHARTER_RETURN_DATE) VALUES (2, 19, NULL, NULL, 2, '2024-08-14', '2024-08-18', '2024-08-17');
INSERT INTO CHARTER (BOAT_ID, CUST_ID, CREW_ID, ITINERARY_ID, WEATHER_ID, CHARTER_START_DATE, CHARTER_END_DATE, CHARTER_RETURN_DATE) VALUES (3, 17, NULL, NULL, 1, '2024-09-01', '2024-09-05', '2024-09-04');
INSERT INTO CHARTER (BOAT_ID, CUST_ID, CREW_ID, ITINERARY_ID, WEATHER_ID, CHARTER_START_DATE, CHARTER_END_DATE, CHARTER_RETURN_DATE) VALUES (5, 11, NULL, NULL, 1, '2024-10-01', '2024-10-03', '2024-10-03');

-- EMPLOYEE rows
INSERT INTO EMPLOYEE (EMPLOYEE_FNAME, EMPLOYEE_LNAME, EMPLOYEE_EMAIL, EMPLOYEE_USERNAME, EMPLOYEE_PASSWORD, EMPLOYEE_JOIN_DATE) VALUES ('Michael', 'Dawson', 'michael.dawson@sailboat.com', 'michael', 'michaeld', '2022-01-01');
INSERT INTO EMPLOYEE (EMPLOYEE_FNAME, EMPLOYEE_LNAME, EMPLOYEE_EMAIL, EMPLOYEE_USERNAME, EMPLOYEE_PASSWORD, EMPLOYEE_JOIN_DATE) VALUES ('Charles', 'Widmore', 'charles.widmore@sailboat.com', 'charles', 'charlesw', '2023-02-15');
INSERT INTO EMPLOYEE (EMPLOYEE_FNAME, EMPLOYEE_LNAME, EMPLOYEE_EMAIL, EMPLOYEE_USERNAME, EMPLOYEE_PASSWORD, EMPLOYEE_JOIN_DATE) VALUES ('Ethan', 'Rom', 'ethan.rom@sailboat.com', 'ethan', 'ethanr', '2023-03-10');
INSERT INTO EMPLOYEE (EMPLOYEE_FNAME, EMPLOYEE_LNAME, EMPLOYEE_EMAIL, EMPLOYEE_USERNAME, EMPLOYEE_PASSWORD, EMPLOYEE_JOIN_DATE) VALUES ('Miles', 'Straume', 'miles.straume@sailboat.com', 'miles', 'miless', '2021-04-20');
INSERT INTO EMPLOYEE (EMPLOYEE_FNAME, EMPLOYEE_LNAME, EMPLOYEE_EMAIL, EMPLOYEE_USERNAME, EMPLOYEE_PASSWORD, EMPLOYEE_JOIN_DATE) VALUES ('Martin', 'Keamy', 'martin.keamy@sailboat.com', 'martin', 'martink', '2023-04-20');


/*



The following creates stored procedures for the application



*/


-- Stored Procedure which checks if the boat is currently on a charter and if it is not it inserts the dates into the CHARTER table

DROP PROCEDURE IF EXISTS Add_Charter;
DROP PROCEDURE IF EXISTS Return_Charter;
DROP PROCEDURE IF EXISTS Add_Customer;

GO

DELIMITER $$

CREATE PROCEDURE Add_Charter (
	IN IN_BOAT_ID INT, 
	IN IN_StartDate DATE, 
	IN IN_EndDate DATE,
	IN IN_CUST_ID INT,
	OUT OUT_RESULT INT,
    OUT MESSAGE VARCHAR(100)
	)
BEGIN
	DECLARE OutputResponse VARCHAR(20) DEFAULT 'available';
	DECLARE temp_start_date DATE;
    DECLARE temp_end_date DATE;
    DECLARE done INT DEFAULT FALSE;
    
    DECLARE charter_temp CURSOR FOR
		SELECT CHARTER_START_DATE, CHARTER_END_DATE
        FROM CHARTER
        WHERE BOAT_ID = IN_BOAT_ID;
        
-- Declare the handler for when there are no more rows to fetch
    DECLARE CONTINUE HANDLER FOR NOT FOUND SET done = TRUE;
        
	OPEN charter_temp;
    
    start_loop : LOOP
		FETCH charter_temp INTO temp_start_date, temp_end_date;
        IF done THEN
			LEAVE start_loop;
		END IF;
    
		IF IN_EndDate >= temp_start_date AND IN_StartDate <= temp_end_date THEN
			SET OutputResponse = 'unavailable';
			SET OUT_RESULT = -1;
            SET MESSAGE = 'unavailable';
			LEAVE start_loop;
		END IF;
    END LOOP;
    
    CLOSE charter_temp;
    
	IF OutputResponse = 'available' 
	THEN
		INSERT INTO CHARTER (BOAT_ID, CUST_ID, CREW_ID, ITINERARY_ID, WEATHER_ID, CHARTER_START_DATE, CHARTER_END_DATE, CHARTER_RETURN_DATE)
		VALUES (IN_BOAT_ID, IN_CUST_ID, NULL, NULL, NULL, IN_StartDate, IN_EndDate, NULL);
		SET MESSAGE = 'Your charter has been booked!';
        
		SET OUT_RESULT = (SELECT CHARTER_ID FROM CHARTER WHERE BOAT_ID = IN_BOAT_ID AND CHARTER_START_DATE = IN_StartDate);
		
	END IF;
END$$

/*
Test Code for Add_Charter

Make the 2nd date after current date

    CALL Add_Charter(3, '2024-09-30', '2024-10-05', 3, @id, @output);
    SELECT CONCAT('Charter Id: ', @id);
    SELECT @output;
    
Make the 2nd date the current date    
    
    CALL Add_Charter(4, '2024-09-30', '2024-10-2', 6, @id, @output);
    SELECT CONCAT('Charter Id: ', @id);
    SELECT @output;
    
Make the 2nd date before the current date

	CALL Add_Charter(1, '2024-09-30', '2024-10-1', 5, @id, @output);
    SELECT CONCAT('Charter Id: ', @id);
    SELECT @output;

*/	


-- Stored Procedure for returning boat and charging the customer

DROP PROCEDURE IF EXISTS Return_Charter;
GO

DELIMITER $$

CREATE PROCEDURE Return_Charter (
	IN IN_CHARTER_ID INT,
	OUT OUT_RESULT VARCHAR(1000)
	)
BEGIN
	DECLARE x_CUST_ID INT;
	DECLARE x_StartDate DATE;
	DECLARE x_EndDate Date;
	DECLARE x_BoatCost DECIMAL;
	DECLARE x_ReturnedAlready DATE;
	DECLARE x_ReturnDate DATE;
	DECLARE x_DaysUsed INT;
	DECLARE x_DaysPastDueDate INT;
	DECLARE x_Charge DECIMAL;
    
	-- This catches for if the wrong charter id was inputted
	DECLARE EXIT HANDLER FOR NOT FOUND
	SET OUT_RESULT = 'No data found for the given charter ID';

	SET x_ReturnDate = CURDATE();
    SET x_ReturnedAlready = NULL;
	
	SELECT A.CUST_ID, A.CHARTER_START_DATE, A.CHARTER_END_DATE, B.BOAT_RENTAL_COST, A.CHARTER_RETURN_DATE
	INTO x_Cust_ID, x_StartDate, x_EndDate, x_BoatCost, x_ReturnedAlready
	FROM CHARTER A
	JOIN BOAT B ON A.BOAT_ID = B.BOAT_ID
	WHERE A.CHARTER_ID = IN_CHARTER_ID;
						

	SET x_DaysUsed = DATEDIFF(x_EndDate, x_StartDate) + 1;

    IF x_ReturnedAlready != NULL
	THEN
		SET OUT_RESULT = 'The boat was not returned';
        
	ELSEIF x_ReturnedAlready IS NULL
	THEN

		IF x_ReturnDate > x_EndDate
		THEN
			SET x_DaysPastDueDate = TRUNCATE(x_ReturnDate - x_EndDate,0);
			SET x_Charge = (x_DaysUsed * x_BoatCost) + (x_DaysPastDueDate * 100);
			SET OUT_RESULT = CONCAT('Your boat has been returned and you have been charged $', CONVERT(x_DaysUsed * x_BoatCost, CHAR), '. There is also a late fee of $', CONVERT(x_DaysPastDueDate * 100, CHAR), '. For a total charge of: $', CONVERT(x_Charge,  CHAR));
		ELSEIF x_ReturnDate < x_EndDate
		THEN
			SET x_DaysPastDueDate = TRUNCATE(x_EndDate - x_ReturnDate,0) + 1;
			SET x_Charge = (x_DaysUsed * x_BoatCost) - (x_DaysPastDueDate * 25);
			SET OUT_RESULT = CONCAT('Your boat has been returned early! The Default cost was: $', CONVERT(x_DaysUsed * x_BoatCost, CHAR), ', but you have received a discount of $', CONVERT(x_DaysPastDueDate * 25, CHAR), '. For a total charge of: $', CONVERT(x_Charge,  CHAR));
		ELSE
			SET x_Charge = (x_DaysUsed * x_BoatCost);
			SET OUT_RESULT = CONCAT('Your boat was returned on time! You have been charged $', CONVERT(x_Charge, CHAR));
		END IF;
		
		UPDATE CUSTOMER
		SET CUST_BALANCE = CUST_BALANCE + x_Charge
		WHERE CUST_ID = x_CUST_ID;
		
		UPDATE CHARTER
		SET CHARTER_RETURN_DATE = x_ReturnDate
		WHERE CHARTER_ID = IN_CHARTER_ID;
	END IF;	
	
END $$



/*
Test Code for Return_Charter

Shows Early Return
    
    CALL RETURN_CHARTER(9 , @output);
    SELECT @output;
    
Shows On Time Return    
    
    CALL RETURN_CHARTER(10 , @output);
    SELECT @output;
    
Shows Late Return    
    
    CALL RETURN_CHARTER(11 , @output);
    SELECT @output;
    


*/


-- Stored procedure to add a new customer into the database. It also returns the CUST_ID

DROP PROCEDURE IF EXISTS Add_Customer;

GO

DELIMITER $$

CREATE PROCEDURE Add_Customer (
	IN IN_CUST_FNAME VARCHAR(20),
	IN IN_CUST_LNAME VARCHAR(20),
	IN IN_CUST_EMAIL VARCHAR(50),
    OUT OUT_RESULT VARCHAR(100)
	)
BEGIN
DECLARE x_CUST_EMAIL VARCHAR(100) DEFAULT 'Currently Available';
DECLARE	x_CUST_ID INT;

SET OUT_RESULT = '';

	SELECT CUST_EMAIL
	INTO x_CUST_EMAIL
	FROM CUSTOMER
	WHERE CUST_EMAIL = IN_CUST_EMAIL;
	
        
	IF x_CUST_EMAIL = IN_CUST_EMAIL
	THEN
		SET OUT_RESULT = 'This email is currently being used. ';
	ELSE
		INSERT INTO CUSTOMER (CUST_FNAME, CUST_LNAME, CUST_EMAIL, CUST_BALANCE) VALUES (IN_CUST_FNAME, IN_CUST_LNAME, IN_CUST_EMAIL, 0.00);
	END IF;
		
		SELECT CUST_ID
		INTO x_CUST_ID
		FROM CUSTOMER
		WHERE CUST_EMAIL = IN_CUST_EMAIL;
		
	SET OUT_RESULT = CONCAT(OUT_RESULT, 'Your Customer ID is: ', CONVERT(x_CUST_ID, CHAR));
		
END$$




/*
Test Code for Add_Customer

This should be return the Customer ID

    CALL Add_Customer('Jonathan', 'Locke', 'John.Locke@gmail.com', @output);
    SELECT @output;
    
This should go through   
   
    CALL Add_Customer('Boone', 'Rutherford', 'Boone.Rutherford@gmail.com', @output);
	SELECT @output;
    
/    

*/