
-- OWNNER rows 
INSERT INTO OWNER (OWNER_FNAME, OWNER_LNAME, OWNER_EMAIL, OWNER_JOIN_DATE) VALUES('Jack', 'Shephard', 'Jack.Shepard@Oceanic.com', '2019-12-03');
INSERT INTO OWNER (OWNER_FNAME, OWNER_LNAME, OWNER_EMAIL, OWNER_JOIN_DATE) VALUES('Kate', 'Austen', 'Kate.Austen@Oceanic.com', '2017-05-11');
INSERT INTO OWNER (OWNER_FNAME, OWNER_LNAME, OWNER_EMAIL, OWNER_JOIN_DATE) VALUES('Hugo', 'Reyes', 'Hugo.Reyes@Oceanic.com', '2018-12-29');
INSERT INTO OWNER (OWNER_FNAME, OWNER_LNAME, OWNER_EMAIL, OWNER_JOIN_DATE) VALUES('Sayid', 'Jarrah', 'Sayid.Jarrah@Oceanic.com', '2017-11-07');
INSERT INTO OWNER (OWNER_FNAME, OWNER_LNAME, OWNER_EMAIL, OWNER_JOIN_DATE) VALUES('Sun-Hwa', 'Kwon', 'Sun-Hwa.Kwon@Oceanic.com', '2020-03-20');
INSERT INTO OWNER (OWNER_FNAME, OWNER_LNAME, OWNER_EMAIL, OWNER_JOIN_DATE) VALUES('Aaron', 'Littleton', 'Aaron.Littleton@Oceanic.com', '2021-11-01');

-- EQUIPMENT rows
INSERT INTO EQUIPMENT (EQUIPMENT_DESC, EQUIPMENT_COST, EQUIPMENT_TYPE) VALUES('40in x 12.83in Fully Battened Mainsail', 2389.00, 'Sail');
INSERT INTO EQUIPMENT (EQUIPMENT_DESC, EQUIPMENT_COST, EQUIPMENT_TYPE) VALUES('Levante Downwind Sail', 11543.40, 'Sail');
INSERT INTO EQUIPMENT (EQUIPMENT_DESC, EQUIPMENT_COST, EQUIPMENT_TYPE) VALUES('D12 MAX 78 Rigging Rope', 380.77, 'Lines');
INSERT INTO EQUIPMENT (EQUIPMENT_DESC, EQUIPMENT_COST, EQUIPMENT_TYPE) VALUES('Marlow Double Braid Polyester Marine Rope', 173.62, 'Lines');
INSERT INTO EQUIPMENT (EQUIPMENT_DESC, EQUIPMENT_COST, EQUIPMENT_TYPE) VALUES('ALL-PAX Passenger Life Preserver', 359.00, 'Life Preserver');
INSERT INTO EQUIPMENT (EQUIPMENT_DESC, EQUIPMENT_COST, EQUIPMENT_TYPE) VALUES('30" USCG Ring Buoy', 91.00, 'Life Preserver');
INSERT INTO EQUIPMENT (EQUIPMENT_DESC, EQUIPMENT_COST, EQUIPMENT_TYPE) VALUES('Gibson Home 95-Piece Complete Kitchen Kit', 99.98, 'Kitchen Equipment'); 
INSERT INTO EQUIPMENT (EQUIPMENT_DESC, EQUIPMENT_COST, EQUIPMENT_TYPE) VALUES('Palm Island Bedcover and Shams', 1320.00, 'Bedding');
INSERT INTO EQUIPMENT (EQUIPMENT_DESC, EQUIPMENT_COST, EQUIPMENT_TYPE) VALUES('Navigation Book', 35.00, 'Caribban Provided');

-- BOAT rows
INSERT INTO BOAT (BOAT_NAME, BOAT_SIZE, BOAT_RENTAL_COST, OWNER_ID) VALUES('Gale', 'Small', 235, 6);
INSERT INTO BOAT (BOAT_NAME, BOAT_SIZE, BOAT_RENTAL_COST, OWNER_ID) VALUES('Liberty', 'Medium', 445, 1);
INSERT INTO BOAT (BOAT_NAME, BOAT_SIZE, BOAT_RENTAL_COST, OWNER_ID) VALUES('Serendipity', 'Small', 270, 5);
INSERT INTO BOAT (BOAT_NAME, BOAT_SIZE, BOAT_RENTAL_COST, OWNER_ID) VALUES('Atlantis', 'Medium', 510, 4);
INSERT INTO BOAT (BOAT_NAME, BOAT_SIZE, BOAT_RENTAL_COST, OWNER_ID) VALUES('Leviathan', 'Large', 975, 3);
INSERT INTO BOAT (BOAT_NAME, BOAT_SIZE, BOAT_RENTAL_COST, OWNER_ID) VALUES('Neptune', 'Large', 850, 3);
INSERT INTO BOAT (BOAT_NAME, BOAT_SIZE, BOAT_RENTAL_COST, OWNER_ID) VALUES('Wayfarer', 'Medium', 480, 2);

-- LOG rows
INSERT INTO LOG (BOAT_ID, EQUIPMENT_ID, LOG_UNITS) VALUES(1, 1, 1);
INSERT INTO LOG (BOAT_ID, EQUIPMENT_ID, LOG_UNITS) VALUES(1, 3, 1);
INSERT INTO LOG (BOAT_ID, EQUIPMENT_ID, LOG_UNITS) VALUES(1, 5, 2);
INSERT INTO LOG (BOAT_ID, EQUIPMENT_ID, LOG_UNITS) VALUES(1, 6, 1);
INSERT INTO LOG (BOAT_ID, EQUIPMENT_ID, LOG_UNITS) VALUES(6, 2, 2);
INSERT INTO LOG (BOAT_ID, EQUIPMENT_ID, LOG_UNITS) VALUES(6, 4, 2);
INSERT INTO LOG (BOAT_ID, EQUIPMENT_ID, LOG_UNITS) VALUES(6, 5, 8);
INSERT INTO LOG (BOAT_ID, EQUIPMENT_ID, LOG_UNITS) VALUES(6, 6, 2);
INSERT INTO LOG (BOAT_ID, EQUIPMENT_ID, LOG_UNITS) VALUES(6, 7, 1);
INSERT INTO LOG (BOAT_ID, EQUIPMENT_ID, LOG_UNITS) VALUES(6, 8, 1);

-- MAINTENANCE rows
INSERT INTO MAINTENANCE (MAINTENANCE_NAME, MAINTENANCE_DESC) VALUES('Sail Patch', 'A temporary patch on the sails.');
INSERT INTO MAINTENANCE (MAINTENANCE_NAME, MAINTENANCE_DESC) VALUES('Hull Repair', 'Fixing extensive damage to the hull.');
INSERT INTO MAINTENANCE (MAINTENANCE_NAME, MAINTENANCE_DESC) VALUES('Rudder Repair', 'Reattaching and testing rudder controls.');
INSERT INTO MAINTENANCE (MAINTENANCE_NAME, MAINTENANCE_DESC) VALUES('Mast Repair', 'Fortifying damaged mast.');
INSERT INTO MAINTENANCE (MAINTENANCE_NAME, MAINTENANCE_DESC) VALUES('Anchor Replacement', 'Replacing anchor and wench');

-- FACILITY rows
INSERT INTO FACILITY (FACILITY_NAME, FACILITY_CITY, FACILITY_STATE) VALUES('Dharma Repairs', 'Fort Meyers', 'FL');
INSERT INTO FACILITY (FACILITY_NAME, FACILITY_CITY, FACILITY_STATE) VALUES('Widmore Marine Parts', 'Pensacola', 'FL');
INSERT INTO FACILITY (FACILITY_NAME, FACILITY_CITY, FACILITY_STATE) VALUES('St. Sebastian Repair', 'Gulfport', 'MS');
INSERT INTO FACILITY (FACILITY_NAME, FACILITY_CITY, FACILITY_STATE) VALUES('Kluck Boat Works', 'Cape Coral', 'FL');
INSERT INTO FACILITY (FACILITY_NAME, FACILITY_CITY, FACILITY_STATE) VALUES('The Island Marine', 'Fort Meyers', 'FL');

-- RECORD rows
INSERT INTO RECORD (BOAT_ID, MAINTENANCE_ID, FACILITY_ID, RECORD_COST) VALUES(1, 1, 2, 139.00);
INSERT INTO RECORD (BOAT_ID, MAINTENANCE_ID, FACILITY_ID, RECORD_COST) VALUES(6, 2, 4, 3475.00);
INSERT INTO RECORD (BOAT_ID, MAINTENANCE_ID, FACILITY_ID, RECORD_COST) VALUES(6, 3, 4, 320.00);
INSERT INTO RECORD (BOAT_ID, MAINTENANCE_ID, FACILITY_ID, RECORD_COST) VALUES(6, 4, 4, 1225.00);
INSERT INTO RECORD (BOAT_ID, MAINTENANCE_ID, FACILITY_ID, RECORD_COST) VALUES(2, 1, 1, 189.99);

-- CREW rows
INSERT INTO CREW (CREW_FNAME, CREW_LNAME, CREW_HOURLY_WAGE) VALUES('Richard', 'Alpert', 35.00);
INSERT INTO CREW (CREW_FNAME, CREW_LNAME, CREW_HOURLY_WAGE) VALUES('Dogen', 'Temple', 42.00);
INSERT INTO CREW (CREW_FNAME, CREW_LNAME, CREW_HOURLY_WAGE) VALUES('Lennon', 'Temple', 38.00);
INSERT INTO CREW (CREW_FNAME, CREW_LNAME, CREW_HOURLY_WAGE) VALUES('Ben', 'Linus', 21.00);
INSERT INTO CREW (CREW_FNAME, CREW_LNAME, CREW_HOURLY_WAGE) VALUES('Juliet', 'Burke', 29.00);

-- WEATHER rows
INSERT INTO WEATHER (WEATHER_DESC, WEATHER_PRECIPITATION, WEATHER_WIND_SPEED) VALUES('Overcast with light rain', 3, 5);
INSERT INTO WEATHER (WEATHER_DESC, WEATHER_PRECIPITATION, WEATHER_WIND_SPEED) VALUES('Sunny clear skies', 0, 4);
INSERT INTO WEATHER (WEATHER_DESC, WEATHER_PRECIPITATION, WEATHER_WIND_SPEED) VALUES('Sunny clear skies with light wind', 0, 9);
INSERT INTO WEATHER (WEATHER_DESC, WEATHER_PRECIPITATION, WEATHER_WIND_SPEED) VALUES('Heavy Storm', 33, 21);
INSERT INTO WEATHER (WEATHER_DESC, WEATHER_PRECIPITATION, WEATHER_WIND_SPEED) VALUES('Overcast with heavy rain', 21, 12);

-- CUSTOMER rows
INSERT INTO CUSTOMER (CUST_FNAME, CUST_LNAME, CUST_EMAIL) VALUES('James', 'Sawyer', 'James.Sawyer@gmail.com');
INSERT INTO CUSTOMER (CUST_FNAME, CUST_LNAME, CUST_EMAIL, CUST_BALANCE) VALUES('Claire', 'Littleton', 'Claire.Littleton@gmail.com', 240.00);
INSERT INTO CUSTOMER (CUST_FNAME, CUST_LNAME, CUST_EMAIL) VALUES('Rose', 'Nadler', 'Rose.Nadler@gmail.com');
INSERT INTO CUSTOMER (CUST_FNAME, CUST_LNAME, CUST_EMAIL, CUST_BALANCE) VALUES('Jin-Soo', 'Kwon', 'Jin-Soo.Kwon@gmail.com', 125.00);
INSERT INTO CUSTOMER (CUST_FNAME, CUST_LNAME, CUST_EMAIL, CUST_BALANCE) VALUES('John', 'Locke', 'John.Locke@gmail.com', 84.00);
INSERT INTO CUSTOMER (CUST_FNAME, CUST_LNAME, CUST_EMAIL, CUST_BALANCE) VALUES('Bernard', 'Nadler', 'Bernard.Nadler@gmail.com', 12.00);
INSERT INTO CUSTOMER (CUST_FNAME, CUST_LNAME, CUST_EMAIL, CUST_BALANCE) VALUES('Shannon', 'Rutherford', 'Shannon.Rutherford@gmail.com', 5000.00);
INSERT INTO CUSTOMER (CUST_FNAME, CUST_LNAME, CUST_EMAIL, CUST_BALANCE) VALUES('Walt', 'Lloyd', 'Walt.Lloyd@gmail.com', 150.00);
INSERT INTO CUSTOMER (CUST_FNAME, CUST_LNAME, CUST_EMAIL, CUST_BALANCE) VALUES('Charlie', 'Pace', 'Charlie.Pace@gmail.com', 230.00);
INSERT INTO CUSTOMER (CUST_FNAME, CUST_LNAME, CUST_EMAIL, CUST_BALANCE) VALUES('Libby', 'Smith', 'Libby.Smith@gmail.com', 45.00);
INSERT INTO CUSTOMER (CUST_FNAME, CUST_LNAME, CUST_EMAIL, CUST_BALANCE) VALUES('Desmond', 'Hume', 'Desmond.Hume@gmail.com', 120.00);
INSERT INTO CUSTOMER (CUST_FNAME, CUST_LNAME, CUST_EMAIL, CUST_BALANCE) VALUES('Nikki', 'Fernandez', 'Nikki.Fernandez@gmail.com', 98.00);
INSERT INTO CUSTOMER (CUST_FNAME, CUST_LNAME, CUST_EMAIL, CUST_BALANCE) VALUES('Daniel', 'Faraday', 'Daniel.Faraday@gmail.com', 250.00);
INSERT INTO CUSTOMER (CUST_FNAME, CUST_LNAME, CUST_EMAIL, CUST_BALANCE) VALUES('Eko', 'Man', 'Eko.Man@gmail.com', 170.00);
INSERT INTO CUSTOMER (CUST_FNAME, CUST_LNAME, CUST_EMAIL, CUST_BALANCE) VALUES('Charlotte', 'Lewis', 'Charlotte.Lewis@gmail.com', 85.00);
INSERT INTO CUSTOMER (CUST_FNAME, CUST_LNAME, CUST_EMAIL, CUST_BALANCE) VALUES('Frank', 'Lapidus', 'Frank.Lapidus@gmail.com', 66.00);
INSERT INTO CUSTOMER (CUST_FNAME, CUST_LNAME, CUST_EMAIL, CUST_BALANCE) VALUES('Ilana', 'Verdansky', 'Ilana.Verdansky@gmail.com', 110.00);
INSERT INTO CUSTOMER (CUST_FNAME, CUST_LNAME, CUST_EMAIL, CUST_BALANCE) VALUES('Eloise', 'Hawking', 'Eloise.Hawking@gmail.com', 30.00);
INSERT INTO CUSTOMER (CUST_FNAME, CUST_LNAME, CUST_EMAIL, CUST_BALANCE) VALUES('Christian', 'Shephard', 'Christian.Shephard@gmail.com', 200.00);
INSERT INTO CUSTOMER (CUST_FNAME, CUST_LNAME, CUST_EMAIL, CUST_BALANCE) VALUES('Penny', 'Widmore', 'Penny.Widmore@gmail.com', 250.00);


-- ITINERARY rows
INSERT INTO ITINERARY (ITINERARY_NAME, ITINERARY_DESC, ITINERARY_LOCATION) VALUES('Coastal Venture', 'Ride along the coast of Florida', 'Florida');
INSERT INTO ITINERARY (ITINERARY_NAME, ITINERARY_DESC, ITINERARY_LOCATION) VALUES('Island Hopping', 'Hop island-to-island on this fun excursion', 'Florida');
INSERT INTO ITINERARY (ITINERARY_NAME, ITINERARY_DESC, ITINERARY_LOCATION) VALUES('Deep Sea Venture', 'Head out to explore the Deep Sea for some remote fun!', 'Mississippi');
INSERT INTO ITINERARY (ITINERARY_NAME, ITINERARY_DESC, ITINERARY_LOCATION) VALUES('Diving Adventure', 'Explore all the beautiful coast reefs and stop by old wreckage', 'Florida');
INSERT INTO ITINERARY (ITINERARY_NAME, ITINERARY_DESC, ITINERARY_LOCATION) VALUES('Exploring the Gulf', 'Set sails and tour all the Gulf has to offer!', 'Mississippi');

-- CHARTER rows
INSERT INTO CHARTER (BOAT_ID, CUST_ID, CREW_ID, ITINERARY_ID, WEATHER_ID, CHARTER_START_DATE, CHARTER_END_DATE, CHARTER_RETURN_DATE) VALUES(1, 7, NULL, 2, 2, '2024-05-12', '2024-05-16', '2024-05-16');
INSERT INTO CHARTER (BOAT_ID, CUST_ID, CREW_ID, ITINERARY_ID, WEATHER_ID, CHARTER_START_DATE, CHARTER_END_DATE, CHARTER_RETURN_DATE) VALUES(1, 2, NULL, 1, 2, '2024-05-15', '2024-05-25', '2024-05-22');
INSERT INTO CHARTER (BOAT_ID, CUST_ID, CREW_ID, ITINERARY_ID, WEATHER_ID, CHARTER_START_DATE, CHARTER_END_DATE, CHARTER_RETURN_DATE) VALUES(2, 5, 1, 3, 2, '2024-06-30', '2024-07-02', '2024-07-03');
INSERT INTO CHARTER (BOAT_ID, CUST_ID, CREW_ID, ITINERARY_ID, WEATHER_ID, CHARTER_START_DATE, CHARTER_END_DATE, CHARTER_RETURN_DATE) VALUES(6, 1, 5, 2, 3, '2024-07-18', '2024-07-21', '2024-07-22');
INSERT INTO CHARTER (BOAT_ID, CUST_ID, CREW_ID, ITINERARY_ID, WEATHER_ID, CHARTER_START_DATE, CHARTER_END_DATE, CHARTER_RETURN_DATE) VALUES(2, 3, 3, 3, 2, '2024-08-21', '2024-08-23', '2024-08-23');
INSERT INTO CHARTER (BOAT_ID, CUST_ID, CREW_ID, ITINERARY_ID, WEATHER_ID, CHARTER_START_DATE, CHARTER_END_DATE, CHARTER_RETURN_DATE) VALUES(4, 4, 5, 5, 1, '2024-08-24', '2024-08-30', '2024-08-30');
INSERT INTO CHARTER (BOAT_ID, CUST_ID, CREW_ID, ITINERARY_ID, WEATHER_ID, CHARTER_START_DATE, CHARTER_END_DATE, CHARTER_RETURN_DATE) VALUES(5, 7, 2, 2, 5, '2024-08-29', '2024-09-05', '2024-09-05');
INSERT INTO CHARTER (BOAT_ID, CUST_ID, CREW_ID, ITINERARY_ID, WEATHER_ID, CHARTER_START_DATE, CHARTER_END_DATE, CHARTER_RETURN_DATE) VALUES(1, 6, NULL, 4, 1, '2024-09-08', '2024-09-11', '2024-09-11');
INSERT INTO CHARTER (BOAT_ID, CUST_ID, CREW_ID, ITINERARY_ID, WEATHER_ID, CHARTER_START_DATE, CHARTER_END_DATE, CHARTER_RETURN_DATE) VALUES(1, 5, NULL, NULL, 1, '2023-03-10', '2023-03-13', '2023-03-12');
INSERT INTO CHARTER (BOAT_ID, CUST_ID, CREW_ID, ITINERARY_ID, WEATHER_ID, CHARTER_START_DATE, CHARTER_END_DATE, CHARTER_RETURN_DATE) VALUES(2, 8, NULL, NULL, 2, '2023-04-05', '2023-04-09', '2023-04-09');
INSERT INTO CHARTER (BOAT_ID, CUST_ID, CREW_ID, ITINERARY_ID, WEATHER_ID, CHARTER_START_DATE, CHARTER_END_DATE, CHARTER_RETURN_DATE) VALUES(3, 14, NULL, NULL, 1, '2023-05-15', '2023-05-18', '2023-05-17');
INSERT INTO CHARTER (BOAT_ID, CUST_ID, CREW_ID, ITINERARY_ID, WEATHER_ID, CHARTER_START_DATE, CHARTER_END_DATE, CHARTER_RETURN_DATE) VALUES(4, 10, NULL, NULL, 2, '2023-06-01', '2023-06-04', '2023-06-03');
INSERT INTO CHARTER (BOAT_ID, CUST_ID, CREW_ID, ITINERARY_ID, WEATHER_ID, CHARTER_START_DATE, CHARTER_END_DATE, CHARTER_RETURN_DATE) VALUES(5, 2, NULL, NULL, 1, '2023-07-20', '2023-07-22', '2023-07-23');
INSERT INTO CHARTER (BOAT_ID, CUST_ID, CREW_ID, ITINERARY_ID, WEATHER_ID, CHARTER_START_DATE, CHARTER_END_DATE, CHARTER_RETURN_DATE) VALUES(6, 16, NULL, NULL, 2, '2023-08-05', '2023-08-07', '2023-08-06');
INSERT INTO CHARTER (BOAT_ID, CUST_ID, CREW_ID, ITINERARY_ID, WEATHER_ID, CHARTER_START_DATE, CHARTER_END_DATE, CHARTER_RETURN_DATE) VALUES(7, 3, NULL, NULL, 1, '2023-09-10', '2023-09-13', '2023-09-12');
INSERT INTO CHARTER (BOAT_ID, CUST_ID, CREW_ID, ITINERARY_ID, WEATHER_ID, CHARTER_START_DATE, CHARTER_END_DATE, CHARTER_RETURN_DATE) VALUES(1, 18, NULL, NULL, 2, '2023-10-08', '2023-10-12', '2023-10-12');
INSERT INTO CHARTER (BOAT_ID, CUST_ID, CREW_ID, ITINERARY_ID, WEATHER_ID, CHARTER_START_DATE, CHARTER_END_DATE, CHARTER_RETURN_DATE) VALUES(2, 4, NULL, NULL, 1, '2023-11-03', '2023-11-06', '2023-11-05');
INSERT INTO CHARTER (BOAT_ID, CUST_ID, CREW_ID, ITINERARY_ID, WEATHER_ID, CHARTER_START_DATE, CHARTER_END_DATE, CHARTER_RETURN_DATE) VALUES(3, 9, NULL, NULL, 2, '2023-12-20', '2023-12-24', '2023-12-23');
INSERT INTO CHARTER (BOAT_ID, CUST_ID, CREW_ID, ITINERARY_ID, WEATHER_ID, CHARTER_START_DATE, CHARTER_END_DATE, CHARTER_RETURN_DATE) VALUES(4, 6, NULL, NULL, 1, '2023-03-25', '2023-03-28', '2023-03-27');
INSERT INTO CHARTER (BOAT_ID, CUST_ID, CREW_ID, ITINERARY_ID, WEATHER_ID, CHARTER_START_DATE, CHARTER_END_DATE, CHARTER_RETURN_DATE) VALUES(5, 19, NULL, NULL, 2, '2023-04-16', '2023-04-18', '2023-04-18');
INSERT INTO CHARTER (BOAT_ID, CUST_ID, CREW_ID, ITINERARY_ID, WEATHER_ID, CHARTER_START_DATE, CHARTER_END_DATE, CHARTER_RETURN_DATE) VALUES(6, 7, NULL, NULL, 1, '2023-05-23', '2023-05-27', '2023-05-26');
INSERT INTO CHARTER (BOAT_ID, CUST_ID, CREW_ID, ITINERARY_ID, WEATHER_ID, CHARTER_START_DATE, CHARTER_END_DATE, CHARTER_RETURN_DATE) VALUES(7, 12, NULL, NULL, 2, '2023-06-19', '2023-06-21', '2023-06-20');
INSERT INTO CHARTER (BOAT_ID, CUST_ID, CREW_ID, ITINERARY_ID, WEATHER_ID, CHARTER_START_DATE, CHARTER_END_DATE, CHARTER_RETURN_DATE) VALUES(1, 11, NULL, NULL, 1, '2023-07-30', '2023-08-02', '2023-08-01');
INSERT INTO CHARTER (BOAT_ID, CUST_ID, CREW_ID, ITINERARY_ID, WEATHER_ID, CHARTER_START_DATE, CHARTER_END_DATE, CHARTER_RETURN_DATE) VALUES(2, 20, NULL, NULL, 2, '2023-09-18', '2023-09-21', '2023-09-20');
INSERT INTO CHARTER (BOAT_ID, CUST_ID, CREW_ID, ITINERARY_ID, WEATHER_ID, CHARTER_START_DATE, CHARTER_END_DATE, CHARTER_RETURN_DATE) VALUES(3, 15, NULL, NULL, 1, '2023-10-22', '2023-10-26', '2023-10-25');
INSERT INTO CHARTER (BOAT_ID, CUST_ID, CREW_ID, ITINERARY_ID, WEATHER_ID, CHARTER_START_DATE, CHARTER_END_DATE, CHARTER_RETURN_DATE) VALUES(4, 13, NULL, NULL, 2, '2023-11-12', '2023-11-16', '2023-11-15');
INSERT INTO CHARTER (BOAT_ID, CUST_ID, CREW_ID, ITINERARY_ID, WEATHER_ID, CHARTER_START_DATE, CHARTER_END_DATE, CHARTER_RETURN_DATE) VALUES(5, 1, NULL, NULL, 1, '2023-12-01', '2023-12-04', '2023-12-03');
INSERT INTO CHARTER (BOAT_ID, CUST_ID, CREW_ID, ITINERARY_ID, WEATHER_ID, CHARTER_START_DATE, CHARTER_END_DATE, CHARTER_RETURN_DATE) VALUES(6, 17, NULL, NULL, 2, '2023-12-27', '2023-12-30', '2023-12-30');
INSERT INTO CHARTER (BOAT_ID, CUST_ID, CREW_ID, ITINERARY_ID, WEATHER_ID, CHARTER_START_DATE, CHARTER_END_DATE, CHARTER_RETURN_DATE) VALUES (1, 3, NULL, NULL, 1, '2024-01-05', '2024-01-07', '2024-01-06');
INSERT INTO CHARTER (BOAT_ID, CUST_ID, CREW_ID, ITINERARY_ID, WEATHER_ID, CHARTER_START_DATE, CHARTER_END_DATE, CHARTER_RETURN_DATE) VALUES (3, 12, NULL, NULL, 2, '2024-01-20', '2024-01-23', '2024-01-22');
INSERT INTO CHARTER (BOAT_ID, CUST_ID, CREW_ID, ITINERARY_ID, WEATHER_ID, CHARTER_START_DATE, CHARTER_END_DATE, CHARTER_RETURN_DATE) VALUES (2, 8, NULL, NULL, 2, '2024-02-15', '2024-02-18', '2024-02-17');
INSERT INTO CHARTER (BOAT_ID, CUST_ID, CREW_ID, ITINERARY_ID, WEATHER_ID, CHARTER_START_DATE, CHARTER_END_DATE, CHARTER_RETURN_DATE) VALUES (4, 18, NULL, NULL, 1, '2024-02-28', '2024-03-02', '2024-03-01');
INSERT INTO CHARTER (BOAT_ID, CUST_ID, CREW_ID, ITINERARY_ID, WEATHER_ID, CHARTER_START_DATE, CHARTER_END_DATE, CHARTER_RETURN_DATE) VALUES (3, 10, NULL, NULL, 1, '2024-03-20', '2024-03-24', '2024-03-23');
INSERT INTO CHARTER (BOAT_ID, CUST_ID, CREW_ID, ITINERARY_ID, WEATHER_ID, CHARTER_START_DATE, CHARTER_END_DATE, CHARTER_RETURN_DATE) VALUES (4, 14, NULL, NULL, 2, '2024-04-10', '2024-04-13', '2024-04-12');
INSERT INTO CHARTER (BOAT_ID, CUST_ID, CREW_ID, ITINERARY_ID, WEATHER_ID, CHARTER_START_DATE, CHARTER_END_DATE, CHARTER_RETURN_DATE) VALUES (5, 16, NULL, NULL, 1, '2024-05-07', '2024-05-10', '2024-05-09');
INSERT INTO CHARTER (BOAT_ID, CUST_ID, CREW_ID, ITINERARY_ID, WEATHER_ID, CHARTER_START_DATE, CHARTER_END_DATE, CHARTER_RETURN_DATE) VALUES (6, 5, NULL, NULL, 2, '2024-06-15', '2024-06-19', '2024-06-18');
INSERT INTO CHARTER (BOAT_ID, CUST_ID, CREW_ID, ITINERARY_ID, WEATHER_ID, CHARTER_START_DATE, CHARTER_END_DATE, CHARTER_RETURN_DATE) VALUES (7, 9, NULL, NULL, 1, '2024-07-22', '2024-07-25', '2024-07-24');
INSERT INTO CHARTER (BOAT_ID, CUST_ID, CREW_ID, ITINERARY_ID, WEATHER_ID, CHARTER_START_DATE, CHARTER_END_DATE, CHARTER_RETURN_DATE) VALUES (1, 20, NULL, NULL, 2, '2024-08-03', '2024-08-06', '2024-08-05');
INSERT INTO CHARTER (BOAT_ID, CUST_ID, CREW_ID, ITINERARY_ID, WEATHER_ID, CHARTER_START_DATE, CHARTER_END_DATE, CHARTER_RETURN_DATE) VALUES (2, 4, NULL, NULL, 1, '2024-09-10', '2024-09-14', '2024-09-13');
INSERT INTO CHARTER (BOAT_ID, CUST_ID, CREW_ID, ITINERARY_ID, WEATHER_ID, CHARTER_START_DATE, CHARTER_END_DATE, CHARTER_RETURN_DATE) VALUES (5, 6, NULL, NULL, 2, '2024-04-25', '2024-04-29', '2024-04-28');
INSERT INTO CHARTER (BOAT_ID, CUST_ID, CREW_ID, ITINERARY_ID, WEATHER_ID, CHARTER_START_DATE, CHARTER_END_DATE, CHARTER_RETURN_DATE) VALUES (6, 15, NULL, NULL, 1, '2024-05-18', '2024-05-22', '2024-05-21');
INSERT INTO CHARTER (BOAT_ID, CUST_ID, CREW_ID, ITINERARY_ID, WEATHER_ID, CHARTER_START_DATE, CHARTER_END_DATE, CHARTER_RETURN_DATE) VALUES (7, 11, NULL, NULL, 2, '2024-06-12', '2024-06-15', '2024-06-14');
INSERT INTO CHARTER (BOAT_ID, CUST_ID, CREW_ID, ITINERARY_ID, WEATHER_ID, CHARTER_START_DATE, CHARTER_END_DATE, CHARTER_RETURN_DATE) VALUES (1, 1, NULL, NULL, 1, '2024-07-05', '2024-07-08', '2024-07-07');
INSERT INTO CHARTER (BOAT_ID, CUST_ID, CREW_ID, ITINERARY_ID, WEATHER_ID, CHARTER_START_DATE, CHARTER_END_DATE, CHARTER_RETURN_DATE) VALUES (2, 19, NULL, NULL, 2, '2024-08-14', '2024-08-18', '2024-08-17');
INSERT INTO CHARTER (BOAT_ID, CUST_ID, CREW_ID, ITINERARY_ID, WEATHER_ID, CHARTER_START_DATE, CHARTER_END_DATE, CHARTER_RETURN_DATE) VALUES (3, 17, NULL, NULL, 1, '2024-09-01', '2024-09-05', '2024-09-04');
INSERT INTO CHARTER (BOAT_ID, CUST_ID, CREW_ID, ITINERARY_ID, WEATHER_ID, CHARTER_START_DATE, CHARTER_END_DATE, CHARTER_RETURN_DATE) VALUES (5, 11, NULL, NULL, 1, '2024-10-01', '2024-10-03', '2024-10-03');

-- EMPLOYEE rows
INSERT INTO EMPLOYEE (EMPLOYEE_FNAME, EMPLOYEE_LNAME, EMPLOYEE_EMAIL, EMPLOYEE_USERNAME, EMPLOYEE_PASSWORD, EMPLOYEE_JOIN_DATE) VALUES ('Michael', 'Dawson', 'michael.dawson@sailboat.com', 'michael', 'michaeld', '2022-01-01');
INSERT INTO EMPLOYEE (EMPLOYEE_FNAME, EMPLOYEE_LNAME, EMPLOYEE_EMAIL, EMPLOYEE_USERNAME, EMPLOYEE_PASSWORD, EMPLOYEE_JOIN_DATE) VALUES ('Charles', 'Widmore', 'charles.widmore@sailboat.com', 'charles', 'charlesw', '2023-02-15');
INSERT INTO EMPLOYEE (EMPLOYEE_FNAME, EMPLOYEE_LNAME, EMPLOYEE_EMAIL, EMPLOYEE_USERNAME, EMPLOYEE_PASSWORD, EMPLOYEE_JOIN_DATE) VALUES ('Ethan', 'Rom', 'ethan.rom@sailboat.com', 'ethan', 'ethanr', '2023-03-10');
INSERT INTO EMPLOYEE (EMPLOYEE_FNAME, EMPLOYEE_LNAME, EMPLOYEE_EMAIL, EMPLOYEE_USERNAME, EMPLOYEE_PASSWORD, EMPLOYEE_JOIN_DATE) VALUES ('Miles', 'Straume', 'miles.straume@sailboat.com', 'miles', 'miless', '2021-04-20');
INSERT INTO EMPLOYEE (EMPLOYEE_FNAME, EMPLOYEE_LNAME, EMPLOYEE_EMAIL, EMPLOYEE_USERNAME, EMPLOYEE_PASSWORD, EMPLOYEE_JOIN_DATE) VALUES ('Martin', 'Keamy', 'martin.keamy@sailboat.com', 'martin', 'martink', '2023-04-20');